---
- name: Install required packages
  ansible.builtin.dnf:
    name:
      - wget
      - curl
      - vim
    state: present

- name: Create MongoDB user
  ansible.builtin.user:
    name: mongodb
    shell: /sbin/nologin
    create_home: false
    state: present

- name: Create MongoDB data directory
  ansible.builtin.file:
    path: /data/mongodb
    state: directory
    owner: mongodb
    group: mongodb
    mode: '0755'